// <auto-generated />
using System;
using Confluence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confluence.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620000000_AddRiskProfileToUserSettings")]
    partial class AddRiskProfileToUserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confluence.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence");

                    b.Property<bool>("ConflictsDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("conflicts_detected");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("LatestPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("latest_price");

                    b.Property<string>("OverallSentiment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overall_sentiment");

                    b.Property<decimal>("OverallSentimentScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_sentiment_score");

                    b.Property<decimal>("RequestedBalance")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("requested_balance");

                    b.Property<decimal>("RequestedRiskPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("requested_risk_percentage");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.HasKey("Id");

                    b.ToTable("analyses");
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_asset");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValue(true);

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("quote_asset");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("pairs");
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<decimal?>("ClosedPnl")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("closed_pnl");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("entry_price");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("exit_price");

                    b.Property<decimal>("InitialSize")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("initial_size");

                    b.Property<decimal?>("Leverage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("leverage");

                    b.Property<string?>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("take_profit");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("trades");
                });

            modelBuilder.Entity("Confluence.Domain.Entities.UserSettings", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id")
                        .HasDefaultValue((short)1);

                    b.Property<decimal>("DefaultBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,8)")
                        .HasDefaultValue(1000m)
                        .HasColumnName("default_balance");

                    b.Property<decimal>("DefaultRiskPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(2.0m)
                        .HasColumnName("default_risk_percentage");

                    b.Property<string>("PreferredTimeframe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("4h")
                        .HasColumnName("preferred_timeframe");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("moderate")
                        .HasColumnName("risk_profile");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("user_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSettings_Singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DefaultBalance = 1000m,
                            DefaultRiskPercentage = 2.0m,
                            PreferredTimeframe = "4h",
                            RiskProfile = "moderate",
                            UpdatedAt = new DateTime(2026, 6, 13, 12, 7, 34, 35, DateTimeKind.Utc).AddTicks(3612)
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Confluence.Domain.Entities.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
