// <auto-generated />
using System;
using Confluence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confluence.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621020000_AddPairManagementSettings")]
    partial class AddPairManagementSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confluence.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence");

                    b.Property<bool>("ConflictsDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("conflicts_detected");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("LatestPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("latest_price");

                    b.Property<string>("OverallSentiment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_sentiment");

                    b.Property<decimal>("OverallSentimentScore")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("overall_sentiment_score");

                    b.Property<decimal>("RequestedBalance")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("requested_balance");

                    b.Property<decimal>("RequestedRiskPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("requested_risk_percentage");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResultJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ResultJson"), "gin");

                    b.HasIndex("Symbol", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Pair", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("base_asset");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("quote_asset");

                    b.HasKey("Symbol");

                    b.ToTable("pairs", (string)null);

                    b.HasData(
                        new
                        {
                            Symbol = "BTC/USDT",
                            BaseAsset = "BTC",
                            CreatedAt = new DateTime(2026, 6, 13, 12, 7, 34, 35, DateTimeKind.Utc).AddTicks(3339),
                            IsActive = true,
                            IsFavorite = true,
                            QuoteAsset = "USDT"
                        },
                        new
                        {
                            Symbol = "ETH/USDT",
                            BaseAsset = "ETH",
                            CreatedAt = new DateTime(2026, 6, 13, 12, 7, 34, 35, DateTimeKind.Utc).AddTicks(3341),
                            IsActive = true,
                            IsFavorite = false,
                            QuoteAsset = "USDT"
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryAmount")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("entry_amount");

                    b.Property<DateTime>("EntryAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("entry_price");

                    b.Property<DateTime?>("ExitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_at");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("exit_price");

                    b.Property<decimal>("Leverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("leverage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tags");

                    b.Property<decimal?>("PnlPercentage")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pnl_percentage");

                    b.Property<decimal?>("PnlQuote")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("pnl_quote");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("take_profit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("Status", "EntryAt")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "Symbol");

                    b.ToTable("trades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trade_Direction", "direction IN ('Long', 'Short')");

                            t.HasCheckConstraint("CK_Trade_Status", "status IN ('Open', 'Closed')");
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.UserSettings", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("id");

                    b.Property<decimal>("DefaultBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,8)")
                        .HasDefaultValue(1000m)
                        .HasColumnName("default_balance");

                    b.Property<decimal>("DefaultRiskPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(2.0m)
                        .HasColumnName("default_risk_percentage");

                    b.Property<string>("PreferredTimeframe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("4h")
                        .HasColumnName("preferred_timeframe");

                    b.Property<string>("PreferredSymbol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("BTC/USDT")
                        .HasColumnName("preferred_symbol");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("moderate")
                        .HasColumnName("risk_profile");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("user_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSettings_Singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DefaultBalance = 1000m,
                            DefaultRiskPercentage = 2.0m,
                            PreferredSymbol = "BTC/USDT",
                            PreferredTimeframe = "4h",
                            RiskProfile = "moderate",
                            UpdatedAt = new DateTime(2026, 6, 13, 12, 7, 34, 35, DateTimeKind.Utc).AddTicks(3612)
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Confluence.Domain.Entities.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
