// <auto-generated />
using System;
using Confluence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confluence.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713221453_AddAiMetadataAndTp2")]
    partial class AddAiMetadataAndTp2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confluence.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence");

                    b.Property<bool>("ConflictsDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("conflicts_detected");

                    b.Property<string>("ConfluenceAlignment")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("confluence_alignment");

                    b.Property<decimal?>("ConfluenceScore")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confluence_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HtfAlignment")
                        .HasColumnType("text");

                    b.Property<decimal>("LatestPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("latest_price");

                    b.Property<string>("LiquidityPoolBias")
                        .HasColumnType("text");

                    b.Property<string>("OverallSentiment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_sentiment");

                    b.Property<decimal>("OverallSentimentScore")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("overall_sentiment_score");

                    b.Property<decimal>("RequestedBalance")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("requested_balance");

                    b.Property<decimal>("RequestedRiskPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("requested_risk_percentage");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.Property<string>("TimeframesAnalyzed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timeframes_analyzed");

                    b.Property<string>("TradeMode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResultJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ResultJson"), "gin");

                    b.HasIndex("Symbol", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("Confluence.Domain.Entities.AnalysisAccuracy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<string>("CheckInterval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("check_interval");

                    b.Property<DateTime>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsAccurate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accurate");

                    b.Property<decimal?>("PotentialPnlPct")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("potential_pnl_pct");

                    b.Property<string>("PredictedDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("predicted_direction");

                    b.Property<decimal>("PriceAtCheck")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("price_at_check");

                    b.Property<decimal>("PriceChangePct")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("price_change_pct");

                    b.Property<bool>("WasMissedOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("was_missed_opportunity");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("AnalysisId", "CheckInterval")
                        .IsUnique();

                    b.ToTable("analysis_accuracies", (string)null);
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Pair", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("base_asset");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("quote_asset");

                    b.HasKey("Symbol");

                    b.ToTable("pairs", (string)null);

                    b.HasData(
                        new
                        {
                            Symbol = "BTC/USDT",
                            BaseAsset = "BTC",
                            CreatedAt = new DateTime(2026, 7, 13, 22, 14, 52, 558, DateTimeKind.Utc).AddTicks(504),
                            IsActive = true,
                            IsFavorite = true,
                            QuoteAsset = "USDT"
                        },
                        new
                        {
                            Symbol = "ETH/USDT",
                            BaseAsset = "ETH",
                            CreatedAt = new DateTime(2026, 7, 13, 22, 14, 52, 558, DateTimeKind.Utc).AddTicks(508),
                            IsActive = true,
                            IsFavorite = false,
                            QuoteAsset = "USDT"
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.StrategyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon_emoji");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preset");

                    b.Property<decimal>("MinimumRR")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("minimum_rr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("NewsWeight")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("news_weight");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_profile");

                    b.Property<string>("TimeframeWeightsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("timeframe_weights_json");

                    b.Property<string>("TimeframesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("timeframes_json");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("IsPreset");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("strategy_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            ColorHex = "#F59E0B",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra short-term trades. Focuses on 15m momentum with 5m/1m timing. High frequency, tight stops, aggressive risk profile.",
                            DisplayName = "Scalp Trading",
                            IconEmoji = "⚡",
                            IsPreset = true,
                            MinimumRR = 1.5m,
                            Name = "scalp",
                            NewsWeight = 0.05m,
                            RiskProfile = "aggressive",
                            TimeframeWeightsJson = "{\"15m\":0.50,\"5m\":0.30,\"1m\":0.20}",
                            TimeframesJson = "[\"1m\",\"5m\",\"15m\"]",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            ColorHex = "#60A5FA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Same-day trades. Uses 4h trend, 1h setup, 15m entry timing. Balanced risk with news awareness.",
                            DisplayName = "Intraday",
                            IconEmoji = "📊",
                            IsPreset = true,
                            MinimumRR = 1.2m,
                            Name = "intraday",
                            NewsWeight = 0.15m,
                            RiskProfile = "moderate",
                            TimeframeWeightsJson = "{\"4h\":0.40,\"1h\":0.35,\"15m\":0.25}",
                            TimeframesJson = "[\"15m\",\"1h\",\"4h\"]",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            ColorHex = "#34D399",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-day trades. Daily macro trend with 4h setup and 1h entry. Higher R:R targets, significant news weight.",
                            DisplayName = "Swing Trading",
                            IconEmoji = "📈",
                            IsPreset = true,
                            MinimumRR = 2.0m,
                            Name = "swing",
                            NewsWeight = 0.25m,
                            RiskProfile = "moderate",
                            TimeframeWeightsJson = "{\"1d\":0.40,\"4h\":0.35,\"1h\":0.25}",
                            TimeframesJson = "[\"1h\",\"4h\",\"1d\"]",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            ColorHex = "#A78BFA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Long-term trend following. Weekly macro + daily setup. Conservative risk, high R:R requirements, fundamental-heavy.",
                            DisplayName = "Position Trading",
                            IconEmoji = "🏛️",
                            IsPreset = true,
                            MinimumRR = 3.0m,
                            Name = "position",
                            NewsWeight = 0.35m,
                            RiskProfile = "conservative",
                            TimeframeWeightsJson = "{\"1w\":0.40,\"1d\":0.35,\"4h\":0.25}",
                            TimeframesJson = "[\"4h\",\"1d\",\"1w\"]",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryAmount")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("entry_amount");

                    b.Property<DateTime>("EntryAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("entry_price");

                    b.Property<decimal?>("EntrySlippagePct")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("entry_slippage_pct");

                    b.Property<string>("EntrySnapshotUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entry_snapshot_url");

                    b.Property<string>("ExecutionQuality")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("execution_quality");

                    b.Property<DateTime?>("ExitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_at");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitSnapshotUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exit_snapshot_url");

                    b.Property<decimal>("Leverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("leverage");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PlannedEntryPrice")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("planned_entry_price");

                    b.Property<decimal?>("PnlPercentage")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pnl_percentage");

                    b.Property<decimal?>("PnlQuote")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("pnl_quote");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tags");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("take_profit");

                    b.Property<decimal?>("TakeProfit2")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("Status", "EntryAt")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "Symbol");

                    b.ToTable("trades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trade_Direction", "direction IN ('Long', 'Short')");

                            t.HasCheckConstraint("CK_Trade_Status", "status IN ('Open', 'Closed')");
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.TradeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("ExecutionScore")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("execution_score");

                    b.Property<string>("FullReviewJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("full_review_json");

                    b.Property<string>("ImprovementAdvice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("improvement_advice");

                    b.Property<bool>("PlanAdherence")
                        .HasColumnType("boolean")
                        .HasColumnName("plan_adherence");

                    b.Property<string>("PlanAdherenceExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_adherence_explanation");

                    b.Property<string>("SlTpAnalysis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sl_tp_analysis");

                    b.Property<bool>("SlTpRational")
                        .HasColumnType("boolean")
                        .HasColumnName("sl_tp_rational");

                    b.Property<string>("TimingExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timing_explanation");

                    b.Property<string>("TimingVerdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("timing_verdict");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("trade_reviews", (string)null);
                });

            modelBuilder.Entity("Confluence.Domain.Entities.UserSettings", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("id");

                    b.Property<decimal>("DefaultBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,8)")
                        .HasDefaultValue(1000m)
                        .HasColumnName("default_balance");

                    b.Property<decimal>("DefaultRiskPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(2.0m)
                        .HasColumnName("default_risk_percentage");

                    b.Property<string>("PreferredSymbol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("BTC/USDT")
                        .HasColumnName("preferred_symbol");

                    b.Property<string>("PreferredTimeframe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("4h")
                        .HasColumnName("preferred_timeframe");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("moderate")
                        .HasColumnName("risk_profile");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("user_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSettings_Singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DefaultBalance = 1000m,
                            DefaultRiskPercentage = 2.0m,
                            PreferredSymbol = "BTC/USDT",
                            PreferredTimeframe = "4h",
                            RiskProfile = "moderate",
                            UpdatedAt = new DateTime(2026, 7, 13, 22, 14, 52, 558, DateTimeKind.Utc).AddTicks(1022)
                        });
                });

            modelBuilder.Entity("Confluence.Domain.Entities.AnalysisAccuracy", b =>
                {
                    b.HasOne("Confluence.Domain.Entities.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Confluence.Domain.Entities.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Confluence.Domain.Entities.TradeReview", b =>
                {
                    b.HasOne("Confluence.Domain.Entities.Trade", "Trade")
                        .WithMany("Reviews")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Confluence.Domain.Entities.Trade", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
