using Microsoft.AspNetCore.SignalR;

namespace Confluence.API.Hubs;

public class AnalysisHub : Hub
{
    /// <summary>
    /// Clients call this method after connecting to subscribe to logs for their specific session.
    /// </summary>
    /// <param name="sessionId">The unique session ID generated by the frontend.</param>
    public async Task JoinSessionGroup(string sessionId)
    {
        await Groups.AddToGroupAsync(Context.ConnectionId, sessionId);
        
        // Confirm connection
        await Clients.Caller.SendAsync("ReceiveSystemMessage", $"Joined telemetry session: {sessionId}");
    }
    
    /// <summary>
    /// Optional: Clients can call this to leave a session group.
    /// </summary>
    public async Task LeaveSessionGroup(string sessionId)
    {
        await Groups.RemoveFromGroupAsync(Context.ConnectionId, sessionId);
    }
}
